name: Build app
run-name: Build app run
on: push
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache maven build
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-m2-repository-cache-${{ hashFiles('**/pom.xml') }}

      - name: Before build - Show project structure
        run: tree $GITHUB_WORKSPACE
      - name: Before build - Show Maven cache
        run: |
          if [ -d ~/.m2 ]; then
                tree -L 4 ~/.m2
          else
                echo "No ~/.m2 directory yet"
          fi

      - name: Build app
        run: mvn clean install -DskipTests=true

      - name: After build - Show project structure
        run: tree $GITHUB_WORKSPACE
      - name: After build - Show Maven cache
        run: |
          if [ -d ~/.m2 ]; then
                tree -L 4 ~/.m2
          else
                echo "No ~/.m2 directory yet"
          fi

      - name: Run tests
        run: mvn test

      - name: After test - Show project structure
        run: tree $GITHUB_WORKSPACE

      - name: Collect report if failed
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-report-${{ github.run_id }}
          path: target/surefire-reports/
          if-no-files-found: ignore
