name: Open issue
run-name: Github issue handler ${{github.event.issue.title}}
on:
  issues:
    types:
      - opened
      - edited
      - closed
jobs:
  issue-handler:
    runs-on: ubuntu-latest
    steps:
      - name: Issue printer
        run: echo "Issue ${{github.event.issue.number}} - ${{github.event.issue.title}} is ${{github.event.issue.state}}"
