name: Branch Name Check

on:
  pull_request:
    branches:
      - main

jobs:
  validate-release-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Validate source branch
        run: |
          BRANCH="${{ github.head_ref }}"

          echo "Branch: $BRANCH"
          if [[ "$BRANCH" =~ ^hotfix/.*$ ]]; then exit 0; fi
          if [[ "$BRANCH" =~ ^release/.*$ ]]; then exit 0; fi

          echo "Invalid branch name"
          exit 1
