name: Build app
run-name: Build app run
on: push
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Show project structure
        run: tree $GITHUB_WORKSPACE
      - name: Show Maven cache
        run: tree -L 4 ~/.m2